base_config:
- config/logging.yaml
- config/wandb.yaml
- config/dataset_normals/dataset_train.yaml
- config/dataset_normals/dataset_val.yaml
- config/dataset_normals/dataset_vis.yaml
- config/model_sdv2.yaml

pipeline:
  name: MarigoldNormalsPipeline
  kwargs:
    default_denoising_steps: 4
    default_processing_resolution: 768

augmentation:
  lr_flip_p: 0.5
  color_jitter_p: 0.3
  gaussian_blur_p: 0.3
  motion_blur_p: 0.3
  gaussian_blur_sigma: 4
  motion_blur_kernel_size: 11
  motion_blur_angle_range: 360
  jitter_brightness_factor: 0.5
  jitter_contrast_factor: 0.5
  jitter_saturation_factor: 0.5
  jitter_hue_factor: 0.2

dataloader:
  num_workers: 2
  effective_batch_size: 32
  max_train_batch_size: 2
  seed: 2024  # to ensure continuity when resuming from checkpoint

trainer:
  name: MarigoldNormalsTrainer
  training_noise_scheduler:
    pretrained_path: stable-diffusion-2
  init_seed: 2024  # use null to train w/o seeding
  save_period: 50
  backup_period: 2000
  validation_period: 500
  visualization_period: 1000

multi_res_noise:
  strength: 0.9
  annealed: true
  downscale_strategy: original

gt_normals_type: normals
gt_mask_type: null

max_epoch: 10000  # a large enough number
max_iter: 30000  # usually converges at around 26k

optimizer:
  name: Adam

loss:
  name: mse_loss
  kwargs:
    reduction: mean

lr: 6.0e-05
lr_scheduler:
  name: IterExponential
  kwargs:
    total_iter: 25000
    final_ratio: 0.01
    warmup_steps: 100

# Light setting for the in-training validation and visualization
validation:
  denoising_steps: 4
  ensemble_size: 1
  processing_res: 768
  match_input_res: true
  resample_method: bilinear
  main_val_metric: mean_angular_error
  main_val_metric_goal: minimize
  init_seed: 0

eval:
  align_max_res: null
  eval_metrics:
  - mean_angular_error
  - sub11_25_error
